services:
  postgress:
    image: postgres:16.1
    restart: "no"
    ports:
      - "5432:5432"
    volumes:
      - postgress_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: Task_Management_System
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 5
volumes:
  postgress_data:
